title: RGB Two Wedding
author: rgbtwo.wedding
email: rgbtwo.wedding@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Your marriage in SF is ready!

twitter_username: rgbtwo.wedding
github_username:  rgbtwo.wedding

sass:
    style: compressed